# Generated by Django 4.0.5 on 2022-06-29 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='loanStatus',
            fields=[
                ('loanStatus_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanStatus_name', models.CharField(max_length=50)),
                ('loanStatus_createdAt', models.DateTimeField()),
                ('loanStatus_updatedAt', models.DateTimeField()),
                ('loanStatus_createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_createdBy', to=settings.AUTH_USER_MODEL)),
                ('loanStatus_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_updatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
