# Generated by Django 4.0.5 on 2022-07-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loanStatus',
            fields=[
                ('loanStatus_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanStatus_name', models.CharField(max_length=50)),
            ],
        ),
    ]
