# Generated by Django 4.0.5 on 2022-06-29 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=50)),
                ('publisher_createdAt', models.DateTimeField()),
                ('publisher_updatedAt', models.DateTimeField()),
                ('publisher_createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_createdBy', to=settings.AUTH_USER_MODEL)),
                ('publisher_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_updatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
