# Generated by Django 4.0.5 on 2022-07-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='object_id',
        ),
    ]
