# Generated by Django 4.0.5 on 2022-06-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_facebook_account_instagram_account_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
