# Generated by Django 4.0.5 on 2022-07-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('author_dateOfBirth', models.DateField()),
                ('author_biography', models.TextField()),
                ('author_imgUrl', models.TextField()),
                ('author_nationalImgUrl', models.TextField()),
                ('author_gender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsRole',
            fields=[
                ('authorRole_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorRole_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
