# Generated by Django 4.0.5 on 2022-07-20 02:24

import apps.authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_pseudonym', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('author_dateOfBirth', models.DateField()),
                ('author_biography', models.TextField()),
                ('author_imgUrl', models.ImageField(blank=True, default=apps.authors.models.get_default_author_image, max_length=255, null=True, upload_to=apps.authors.models.get_author_image_filepath)),
                ('author_gender', models.BooleanField()),
            ],
        ),
    ]
