# Generated by Django 4.0.5 on 2022-07-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_bookauthorship_book_author_ship_combination_and_more'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorsRole',
        ),
    ]
