# Generated by Django 4.0.5 on 2022-07-13 03:11

import apps.authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_delete_authorsrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='author_nationalImgUrl',
        ),
        migrations.AlterField(
            model_name='authors',
            name='author_imgUrl',
            field=models.ImageField(blank=True, default=apps.authors.models.get_default_author_image, max_length=255, null=True, upload_to=apps.authors.models.get_author_image_filepath),
        ),
    ]
