# Generated by Django 4.0.5 on 2022-07-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_remove_authors_author_nationalimgurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='author_pseudonym',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
