# Generated by Django 4.0.5 on 2022-06-27 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
                ('genre_description', models.TextField(max_length=1000)),
                ('genre_code', models.CharField(max_length=10)),
                ('genre_updatedAt', models.DateTimeField()),
                ('genre_createdAt', models.DateTimeField()),
                ('genre_createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_createdBy', to=settings.AUTH_USER_MODEL)),
                ('genre_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_updatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('theme_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=50)),
                ('theme_description', models.CharField(max_length=255)),
                ('theme_createdAt', models.DateTimeField()),
                ('theme_updatedAt', models.DateTimeField()),
                ('theme_createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_createdBy', to=settings.AUTH_USER_MODEL)),
                ('theme_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_updatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgenre_name', models.CharField(max_length=50)),
                ('subgenre_description', models.TextField(max_length=1000)),
                ('subgenre_code', models.CharField(max_length=10)),
                ('subgenre_updatedAt', models.DateTimeField()),
                ('subgenre_createdAt', models.DateTimeField()),
                ('subgenre_createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subGenre_createdBy', to=settings.AUTH_USER_MODEL)),
                ('subgenre_ofGenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genre.genre')),
                ('subgenre_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subGenre_UpdatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
