# Generated by Django 4.0.5 on 2022-07-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='theme_description',
            field=models.CharField(max_length=1000),
        ),
    ]
