# Generated by Django 4.0.5 on 2022-07-20 02:24

import apps.book.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('loan', '0001_initial'),
        ('genre', '0001_initial'),
        ('publisher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('book_image', models.ImageField(blank=True, default=apps.book.models.get_default_profile_image, max_length=255, null=True, upload_to=apps.book.models.get_profile_image_filepath)),
                ('book_description', models.TextField()),
                ('book_released', models.IntegerField()),
                ('book_amount', models.IntegerField()),
                ('book_pages', models.IntegerField()),
            ],
            options={
                'get_latest_by': ['book_id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=255, unique=True)),
                ('language_code', models.CharField(max_length=5, unique=True)),
                ('language_image', models.ImageField(blank=True, default=apps.book.models.get_default_language_image, max_length=255, null=True, upload_to=apps.book.models.get_language_image_filepath)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='receipt_timestamp')),
                ('receipt_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanedBook',
            fields=[
                ('loanedBook_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanedBook_startDate', models.DateField(blank=True, null=True)),
                ('loanedBook_dueDate', models.DateField(blank=True, null=True)),
                ('loanedBook_returnedDate', models.DateField(blank=True, null=True)),
                ('loanedBook_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanedBook_bookId', to='book.books')),
                ('loanedBook_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanedBook_receipt', to='book.receipt')),
                ('loanedBook_statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanedBook_loanStatus', to='loan.loanstatus')),
            ],
        ),
        migrations.CreateModel(
            name='BookThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookthemes_bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Themes_bookId', to='book.books')),
                ('bookthemes_themeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Themes_themeId', to='genre.themes')),
            ],
        ),
        migrations.CreateModel(
            name='BookSubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksubgenre_bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Subgenre_bookId', to='book.books')),
                ('booksubgenre_subgenreId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Subgenre_subgenreId', to='genre.subgenre')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='book_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_language', to='book.language'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_publisher', to='publisher.publisher'),
        ),
        migrations.CreateModel(
            name='BookAuthorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookauthorship_authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Authorship_authorId', to='authors.authors')),
                ('bookauthorship_bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Authorship_bookId', to='book.books')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bookthemes',
            constraint=models.UniqueConstraint(fields=('bookthemes_bookId', 'bookthemes_themeId'), name='book_themes_combination'),
        ),
        migrations.AddConstraint(
            model_name='booksubgenre',
            constraint=models.UniqueConstraint(fields=('booksubgenre_bookId', 'booksubgenre_subgenreId'), name='book_subgenre_combination'),
        ),
        migrations.AddConstraint(
            model_name='bookauthorship',
            constraint=models.UniqueConstraint(fields=('bookauthorship_bookId', 'bookauthorship_authorId'), name='book_author_ship_combination'),
        ),
    ]
