# Generated by Django 4.0.5 on 2022-07-12 07:29

import apps.book.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genre', '0001_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('book_image', models.ImageField(blank=True, default=apps.book.models.get_default_profile_image, max_length=255, null=True, upload_to=apps.book.models.get_profile_image_filepath)),
                ('book_description', models.CharField(max_length=255)),
                ('book_released', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=255, unique=True)),
                ('language_code', models.CharField(max_length=5, unique=True)),
                ('language_image', models.ImageField(blank=True, default=apps.book.models.get_default_language_image, max_length=255, null=True, upload_to=apps.book.models.get_language_image_filepath)),
            ],
        ),
        migrations.CreateModel(
            name='LoanedBook',
            fields=[
                ('loanedBook_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanedBook_startDate', models.DateField(blank=True, null=True)),
                ('loanedBook_dueDate', models.DateField(blank=True, null=True)),
                ('loanedBook_returnedDate', models.DateField(blank=True, null=True)),
                ('loanedBook_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('loanedBook_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanedBook_bookId', to='book.books')),
                ('loanedBook_statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanedBook_loanStatus', to='loan.loanstatus')),
                ('loanedBook_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanedBook_userId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookthemes_bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Themes_bookId', to='book.books')),
                ('bookthemes_themeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Themes_themeId', to='genre.themes')),
            ],
        ),
        migrations.CreateModel(
            name='BookSubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksubgenre_bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Subgenre_bookId', to='book.books')),
                ('booksubgenre_subgenreId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Subgenre_subgenreId', to='genre.subgenre')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='book_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_language', to='book.language'),
        ),
    ]
