# Generated by Django 4.0.5 on 2022-06-29 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0001_initial'),
        ('genre', '0001_initial'),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('book_image', models.CharField(max_length=255)),
                ('book_description', models.CharField(max_length=255)),
                ('book_language', django_countries.fields.CountryField(max_length=2)),
                ('book_released', models.IntegerField()),
                ('book_updatedAt', models.DateTimeField()),
                ('book_createdAt', models.DateTimeField()),
                ('book_createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_createdBy', to=settings.AUTH_USER_MODEL)),
                ('book_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_publisher', to='publisher.publisher')),
                ('book_updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_updatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookthemes_bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Themes_bookId', to='book.books')),
                ('bookthemes_themeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Themes_themeId', to='genre.themes')),
            ],
        ),
        migrations.CreateModel(
            name='BookSubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksubgenre_bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Subgenre_bookId', to='book.books')),
                ('booksubgenre_subgenreId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Subgenre_subgenreId', to='genre.subgenre')),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookauthorship_authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Authorship_authorId', to='authors.authors')),
                ('bookauthorship_authorRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Authorship_authorRole', to='authors.authorsrole')),
                ('bookauthorship_bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Authorship_bookId', to='book.books')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bookthemes',
            constraint=models.UniqueConstraint(fields=('bookthemes_bookId', 'bookthemes_themeId'), name='book_themes_combination'),
        ),
        migrations.AddConstraint(
            model_name='booksubgenre',
            constraint=models.UniqueConstraint(fields=('booksubgenre_bookId', 'booksubgenre_subgenreId'), name='book_subgenre_combination'),
        ),
        migrations.AddConstraint(
            model_name='bookauthorship',
            constraint=models.UniqueConstraint(fields=('bookauthorship_bookId', 'bookauthorship_authorId', 'bookauthorship_authorRole'), name='book_author_ship_combination'),
        ),
    ]
