# Generated by Django 4.0.5 on 2022-07-12 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('publisher', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_publisher', to='publisher.publisher'),
        ),
        migrations.AddField(
            model_name='bookauthorship',
            name='bookauthorship_authorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Authorship_authorId', to='authors.authors'),
        ),
        migrations.AddField(
            model_name='bookauthorship',
            name='bookauthorship_authorRole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Authorship_authorRole', to='authors.authorsrole'),
        ),
        migrations.AddField(
            model_name='bookauthorship',
            name='bookauthorship_bookId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_Authorship_bookId', to='book.books'),
        ),
        migrations.AddConstraint(
            model_name='bookthemes',
            constraint=models.UniqueConstraint(fields=('bookthemes_bookId', 'bookthemes_themeId'), name='book_themes_combination'),
        ),
        migrations.AddConstraint(
            model_name='booksubgenre',
            constraint=models.UniqueConstraint(fields=('booksubgenre_bookId', 'booksubgenre_subgenreId'), name='book_subgenre_combination'),
        ),
        migrations.AddConstraint(
            model_name='bookauthorship',
            constraint=models.UniqueConstraint(fields=('bookauthorship_bookId', 'bookauthorship_authorId', 'bookauthorship_authorRole'), name='book_author_ship_combination'),
        ),
    ]
