# Generated by Django 4.0.5 on 2022-07-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_bookauthorship_book_author_ship_combination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'get_latest_by': ['book_id']},
        ),
    ]
