# Generated by Django 4.0.5 on 2022-07-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_books_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_description',
            field=models.TextField(),
        ),
    ]
